services:

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
     - .env

  cache:
    image: redis
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--",
              "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
     - .env
    environment:
      - DJANGO_SETTINGS_MODULE=enlearn.settings.prod
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
      - ./certbot/conf/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./certbot/conf/privkey.pem:/etc/nginx/ssl/privkey.pem:ro    
    ports:
      - "80:80"
      - "443:443"
