# Generated by Django 4.2.7 on 2023-11-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0005_remove_wordform_word_remove_description_form_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='meaning',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='description',
            name='translate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='translate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sound',
            name='transcription',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_learning_word', models.CharField(choices=[('Unknown', 'Unknown'), ('Learning_0_stage', 'Learning_0_stage'), ('Learning_1_stage', 'Learning_1_stage'), ('Learning_2_stage', 'Learning_2_stage'), ('Learning_3_stage', 'Learning_3_stage'), ('Learning_4_stage', 'Learning_4_stage'), ('Learning_5_stage', 'Learning_5_stage'), ('Learned', 'Learned')], default='Unknown')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word')),
            ],
        ),
    ]
