# Generated by Django 4.2.7 on 2023-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_word_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['name', 'rank']},
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound',
            field=models.FileField(blank=True, upload_to='media/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
    ]
