# Generated by Django 4.2.7 on 2023-11-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WordSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')])),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('translate', models.CharField(max_length=255)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('adjectival', 'adjectival'), ('noun', 'noun'), ('verb', 'verb')])),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('adjectival', 'Adjectival'), ('noun', 'Noun'), ('verb', 'Verb')])),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('sound', models.FileField(blank=True, upload_to='')),
                ('wordsound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound', to='word.wordsound')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_conditions', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255)),
                ('translate', models.CharField(max_length=255)),
                ('form_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='word.worddescription')),
            ],
        ),
    ]
