# Generated by Django 4.2.7 on 2023-11-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordPhrase',
            new_name='Phrase',
        ),
    ]
