# Generated by Django 4.2.7 on 2023-11-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_rename_wordphrase_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='word.word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='word.word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sound',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='word.word'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_conditions', to='word.wordform'),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word'),
        ),
        migrations.AlterField(
            model_name='wordform',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word'),
        ),
        migrations.AlterField(
            model_name='wordsound',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word'),
        ),
    ]
