# Generated by Django 4.2.7 on 2023-11-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_remove_sound_wordsound_sound_region_alter_sound_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordform',
            name='word',
        ),
        migrations.RemoveField(
            model_name='description',
            name='form_object',
        ),
        migrations.AddField(
            model_name='description',
            name='part_of_speech',
            field=models.CharField(choices=[('adjectival', 'Adjectival'), ('noun', 'Noun'), ('verb', 'Verb')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='part_of_speech',
            field=models.CharField(choices=[('adjectival', 'adjectival'), ('noun', 'noun'), ('verb', 'verb')]),
        ),
        migrations.DeleteModel(
            name='WordDescription',
        ),
        migrations.DeleteModel(
            name='WordForm',
        ),
    ]
