# Generated by Django 4.2.7 on 2023-11-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_alter_description_meaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='rank',
            field=models.CharField(default='20000'),
        ),
    ]
