# Generated by Django 4.2.7 on 2023-11-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_alter_word_options_alter_sound_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='region',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
    ]
