# Generated by Django 4.2.7 on 2023-11-29 13:01

from django.db import migrations, models
import word.models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0010_alter_sound_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to=word.models.sound_path),
        ),
    ]
